# Generated by Django 3.2.8 on 2021-12-03 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211122_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='users', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('CL', 'Clothing'), ('JE', 'Jewelry'), ('RE', 'Record'), ('BO', 'Book'), ('AR', 'Art'), ('IN', 'Instrument'), ('KI', 'Kitchen'), ('DE', 'Decoration'), ('OT', 'Other'), (None, 'Choose a category...')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.URLField(blank=True, max_length=350, validators=[django.core.validators.URLValidator()]),
        ),
    ]
