# Generated by Django 3.2.8 on 2021-12-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211203_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('CL', 'Clothing'), ('JE', 'Jewelries'), ('AC', 'Accessories'), ('RE', 'Records'), ('BO', 'Books'), ('AR', 'Artworks'), ('DE', 'Decorations'), ('IN', 'Instruments'), ('OT', 'Others'), (None, 'Choose a category...')], default=None, max_length=2),
        ),
    ]
