# Generated by Django 3.2.8 on 2021-12-08 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20211207_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchedby',
            field=models.ManyToManyField(blank=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
