# Generated by Django 3.2.8 on 2021-12-15 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_watchedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(default=0, max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='comments', to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='commentedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
