# Generated by Django 3.2.8 on 2021-12-21 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='closed',
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won', to=settings.AUTH_USER_MODEL),
        ),
    ]
